version: "3.8"

services:
  router_rip_0:
    image: frrouting/frr
    container_name: router_rip_0
    hostname: router_rip_0
    privileged: true
    volumes:
      - ./volumes/router_rip_0:/etc/frr
    networks:
      net_rip_1:
        ipv4_address: 192.168.1.1
      net_rip_4:
        ipv4_address: 192.168.4.1

  router_rip_1:
    image: frrouting/frr
    container_name: router_rip_1
    hostname: router_rip_1
    privileged: true
    volumes:
      - ./volumes/router_rip_1:/etc/frr
    networks:
      net_rip_1:
        ipv4_address: 192.168.1.2
      net_rip_2:
        ipv4_address: 192.168.2.1

  router_rip_2:
    image: frrouting/frr
    container_name: router_rip_2
    hostname: router_rip_2
    privileged: true
    volumes:
      - ./volumes/router_rip_2:/etc/frr
    networks:
      net_rip_2:
        ipv4_address: 192.168.2.2
      net_rip_3:
        ipv4_address: 192.168.3.1

  router_rip_3:
    image: frrouting/frr
    container_name: router_rip_3
    hostname: router_rip_3
    privileged: true
    volumes:
      - ./volumes/router_rip_3:/etc/frr
    networks:
      net_rip_3:
        ipv4_address: 192.168.3.2
      net_rip_4:
        ipv4_address: 192.168.4.2

  router_ospf_0:
    image: frrouting/frr
    container_name: router_ospf_0
    hostname: router_ospf_0
    privileged: true
    volumes:
      - ./volumes/router_ospf_0:/etc/frr
    networks:
      net_ospf_1:
        ipv4_address: 192.168.5.1
      net_ospf_4:
        ipv4_address: 192.168.8.1

  router_ospf_1:
    image: frrouting/frr
    container_name: router_ospf_1
    hostname: router_ospf_1
    privileged: true
    volumes:
      - ./volumes/router_ospf_1:/etc/frr
    networks:
      net_ospf_1:
        ipv4_address: 192.168.5.2
      net_ospf_2:
        ipv4_address: 192.168.6.1

  router_ospf_2:
    image: frrouting/frr
    container_name: router_ospf_2
    hostname: router_ospf_2
    privileged: true
    volumes:
      - ./volumes/router_ospf_2:/etc/frr
    networks:
      net_ospf_2:
        ipv4_address: 192.168.6.2
      net_ospf_3:
        ipv4_address: 192.168.7.1

  router_ospf_3:
    image: frrouting/frr
    container_name: router_ospf_3
    hostname: router_ospf_3
    privileged: true
    volumes:
      - ./volumes/router_ospf_3:/etc/frr
    networks:
      net_ospf_3:
        ipv4_address: 192.168.7.2
      net_ospf_4:
        ipv4_address: 192.168.8.2

networks:
  net_rip_1:
    name: net_rip_1
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254

  net_rip_2:
    name: net_rip_2
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254
  net_rip_3:
    name: net_rip_3
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.254
  net_rip_4:
    name: net_rip_4
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.4.0/24
          gateway: 192.168.4.254
  net_ospf_1:
    name: net_ospf_1
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.254
  net_ospf_2:
    name: net_ospf_2
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.6.0/24
          gateway: 192.168.6.254
  net_ospf_3:
    name: net_ospf_3
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.7.0/24
          gateway: 192.168.7.254
  net_ospf_4:
    name: net_ospf_4
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.8.0/24
          gateway: 192.168.8.254
